version: "3.8"

services:
  prometheus:
    image: prom/prometheus:latest
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager  # Prometheus doit tourner sur un nœud manager
      restart_policy:
        condition: on-failure
    ports:
      - "9090:9090"  # Port Prometheus
    volumes:
      - prometheus_data:/prometheus  # Données persistance de Prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro  # Configuration en lecture seule
    networks:
      - monitoring

  node-exporter:
    image: prom/node-exporter:latest
    deploy:
      mode: global  # Une instance sur chaque nœud
      restart_policy:
        condition: on-failure
    ports:
      - target: 9100
        published: 9100
        protocol: tcp
        mode: host  # Exposition directe sur l'hôte
    command:
      - '--path.rootfs=/host'  # Collecter les métriques système
    volumes:
      - /proc:/host/proc:ro  # Statistiques système
      - /sys:/host/sys:ro    # Informations sur le matériel
      - /:/host:ro           # Accès au système de fichiers
    networks:
      - monitoring

volumes:
  prometheus_data:
    driver: local

networks:
  monitoring:
    driver: overlay


